### ISSUE TITLE
How to change the name of my chatbot

### ISSUE THREAD

**Issue by LooksForFuture** [ahmadfaizalbh/Chatbot#12]
Hi. I want to change the chatbot's name from "ChatBot" to "something".
How should I do this?

**Comment by LooksForFuture** [comment]
Hi. I want to change the chatbot's name from "ChatBot" to "something".
How should I do this?

**Comment by ahmadfaizalbh** [comment]
In your `.template` file add below code

```
{% block %}
    {% client %}What is your name{% endclient %}
    {% response %}My name is ChatBot{% endresponse %}
{% endblock %}
```

**Comment by LooksForFuture** [comment]
Thanks😉

**Comment by LooksForFuture** [comment]
HI, I have another problem too.
When I use Chat._startNewSession("User") it want a "self" from me.
I do not known what should I do.

**Comment by ahmadfaizalbh** [comment]
You should use Chat object to create new session.

```python 
chat = Chat(os.path.join(os.path.dirname(os.path.abspath(__file__)),"Example.template"))
chat._startNewSession("User") 
```
