### ISSUE TITLE
Middleware for handling chatbot response?

### ISSUE THREAD

**Issue by divy-work** [ahmadfaizalbh/Chatbot#20]
Is there any way I can handle the chatbot's response using a middleware function or something like that?
Great repo by the way :)

**Comment by ahmadfaizalbh** [comment]
If you are looking to make it as web application then checkout example Django application [https://github.com/ahmadfaizalbh/WebBot](https://github.com/ahmadfaizalbh/WebBot)


If you want to create middleware, I would need more information about what kind of middleware you are looking at how you want the middleware to function etc. to help you with the same.

if you don't want to disclose details here you can always email me at [ahmadfaizalbh726@gmail.com](mailto:ahmadfaizalbh726@gmail.com)

**Comment by divy-work** [comment]
I actually need to pass all the response of the chatbot to a text to speech engine.

```python
def speak(msg):
  # I run a command here to trigger a script for text to speech
```

But I can't a way to obtain every response of the chatbot. Is there a way to do that?

Thanks.

**Comment by ahmadfaizalbh** [comment]
You can in inherit Chat and override conversation


```python
from chatbot import Chat

class MyChat(Chat):
    def converse(self, first_question=None, quit="quit", session_id="general"):
        """
        Conversation initiator
        :type first_question: str
        :param first_question: Start up message
        :type quit: str
        :param quit: Conversation termination command
        :type session_id: str
        :param session_id: Current User session when used for multi user scenario
        :rtype: str
        """
        if first_question:
            self.conversation[session_id].append(first_question)
            print(first_question)
        input_sentence = ""
        while input_sentence != quit:
            # Read Input source
            input_sentence = input("> ")
            if input_sentence:
                self.conversation[session_id].append(input_sentence)
                input_sentence = input_sentence.rstrip("!.")
                message = self.respond(input_sentence, session_id=session_id)
                self.conversation[session_id].append(message)
                # call output function
                speak(message)

first_question = "Hi, how are you?"
chat = MyChat(os.path.join(os.path.dirname(os.path.abspath(__file__)), "Example.template"))
chat.converse(first_question)
```

if you have any voice listener function that returns user text then replace `input` with listener function

**Comment by divy-work** [comment]
Oh okay! I'll give it a try and get back to you. Thanks

**Comment by divy-work** [comment]
Thanks dude :+1: It worked just fine.

I have another question I'll open another issue for that.
