### ISSUE TITLE
Execution

### ISSUE THREAD

**Issue by NaterciaMR** [ahmadfaizalbh/Chatbot#22]
Hi,

I would like to execute chatbot program without linux cmd. I'm using windows 10.
I cloned and installed it but I tried to execute setup.py like this way:
 C:\Windows\System32\Chatbot>py setup.py
but the response was: 
C:\Windows\System32\Chatbot>chatbot import demo
"chatbot" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

Thanks!

**Comment by ahmadfaizalbh** [comment]
do the following

# Installing the package

```
C:\Windows\System32\Chatbot>py setup.py install
```
OR

```
C:\Windows\System32\Chatbot>pip install chatbotai
```

# Running demo function
```
C:\Windows\System32\Chatbot>py
```
```python
>>> from chatbot import demo
>>> demo()
Hi, how are you?
> i'm fine
Nice to know that you are fine  
> quit
Thank you for talking with me.
>>> 
```

Chatbot is not a command instead its a python library

**Comment by NaterciaMR** [comment]
thank you but now, I received this:

 >>> from chatbot import demo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'chatbot'

thanks for you help and I'm so sorry.

**Comment by ahmadfaizalbh** [comment]
That means you have not installed chatbot 
To install chatbot execute 
```
C:\Windows\System32\Chatbot>py setup.py install
```

**Comment by NaterciaMR** [comment]
I could do it doing the following:

C:\Windows\System32\Chatbot>python setup.py install
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from chatbot import demo
>>> demo()
Hi, how are you?
>

Thank you!

**Comment by NaterciaMR** [comment]
One last question, how can I run it in Portuguese? I have seen there is a pt.template

**Comment by ahmadfaizalbh** [comment]
Its Portuguese (Brazil),  you can use as follows

```python
>>> demo(language="pt-br")
```

Since I don't know  Portuguese (Brazil) I couldn't add any normalizer and reflections. I translated temple file using google translate for one of the user on request. If you know any language (Portuguese) and willing to spend some time you can contribute to the repo which will be helpful for many.

**Comment by NaterciaMR** [comment]
I'm portuguese and live in Spain (Madrid). Of course, I would like to participate. At the moment, I am doing a job about training manuals in Spanish for my college.

**Comment by ahmadfaizalbh** [comment]
Thats great.
If you need any help feel free to email me at ahmadfaizalbh726@gmail.com

**Comment by NaterciaMR** [comment]
oh thanks! my email is naterciamr18@gmail.com
