### ISSUE TITLE
Functions registered via register_call can not access variables

### ISSUE THREAD

**Issue by padmalcom** [ahmadfaizalbh/Chatbot#29]
Hi, first of all thank you for your great library. I have several variables managed in my python script and I try to access those variables in functions that I register using register_call. But it seems that they are never updated within the function.

An example:
```
current_speaker = None

@register_call("iam")
def iam(name, session_id = "general"):
	if current_speaker == None:
		return "Nice to meet you " + name
	else:
		return "I already know you " + name
```

Here, current_speaker is always None, no matter if I set it or not.

What are my options to get a global variable into such a function?

**Comment by ahmadfaizalbh** [comment]
where are you setting variable `current_speaker` to non None value?

**Comment by padmalcom** [comment]
In my main function, let me give you an example. I tried to reduce my code as far as possible. I do not use any classes and I double checked that current_speaker is set via prints. It seems that it is once registered in the function iam and never changed from there on.

```
current_speaker = None
chat = Chat(DIALOG_TEMPLATE)


@register_call("iam")
def iam(name, session_id = "general"):
	if current_speaker == None:
		return "Nice to meet you " + name
	else:
		return "I already know you " + name

def main():
	current_speaker = "Nick"
	output = chat.respond("My name is Nick.")

if __name__ == '__main__':
	main()
```

**Comment by ahmadfaizalbh** [comment]
your variable `current_speaker` is a local variable in `main` function which will not be accessible from `iam` function to make current code work you have to add  `global current_speaker` at beginning of `main` function as below

**Comment by ahmadfaizalbh** [comment]
if you are trying to do it for multiple users for each user create a new session using `start_new_session(session_id, topic)` function and call as followers `respond("My name is Nick.", session_id)` where `session_id` can be any unique id identifier that can identify the current speaker.
