### ISSUE TITLE
Add examples for features in template files

### ISSUE THREAD

**Issue by padmalcom** [ahmadfaizalbh/Chatbot#32]
I use chatbotai successfully, but in a very simple way (mostly, the client says something and the bot respondes).

Nevertheless, I'm very curious regarding all the features listed in "List of feature supported in bot template" and I'd like to use them but I'm missing some clear examples. Could you provide some?

**Comment by ahmadfaizalbh** [comment]
check [default.template](https://github.com/ahmadfaizalbh/Chatbot/blob/9053a32581e08b5740676314b95081d49d276ee5/chatbot/local/en/default.template) to see couple of features usage.

I will be adding more examples to cover all features and their usage.

**Comment by padmalcom** [comment]
The hint to look at default.template is great, most features make sense now.
