### ISSUE TITLE
Can not avoid "default" answers from default.template

### ISSUE THREAD

**Issue by padmalcom** [ahmadfaizalbh/Chatbot#34]
I wrote a bot that speaks German. Whenever the bot does not understand, it generates an English answer from the English default.template. I could not find a way to avoid that. Can you help me out?

**Comment by ahmadfaizalbh** [comment]
pass `default_template` while initiating `Chat`

`Chat("examples/Example.template", default_template=<path to default template>)`

please refer English version of default template https://github.com/ahmadfaizalbh/Chatbot/blob/master/chatbot/local/en/default.template 

it would be appreciable if you could help in adding German (de) language support to do that add `default.template`, `substitutions.json`, and `words.txt` in  `chatbot/local/de/` where `words.txt` is dictionary words list for spell correction.

**Comment by padmalcom** [comment]
Oh okay, default_template is a good hint.

Sure, I can do that :)

**Comment by padmalcom** [comment]
I created a pull request (https://github.com/ahmadfaizalbh/Chatbot/pull/35) and know how to replace the default template. This can be closed.
